baseURL = "https://torrytw.ooo"
publishDir = "docs"
title = "torry2"
theme = "etch"
languageCode = "en"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  dark = "auto"
  homepage = "https://torrytw.ooo"
  description = "internet website"
  tags = ["web", "site"]
  highlight = true
  copyright = "Copyright © 2022 torrytwooo"
  license = "The Unlicense"
  licenselink = "https://github.com/torry2/torry2.github.io/blob/main/LICENSE"

[taxonomies]
    tag = "tags"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags/"
    weight = 20   

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 30
     
[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # html enabled in md
  unsafe = true
  
  
[author]
  name = "torrytwooo"
  homepage = "https://torrytw.ooo"